# Generated by Django 6.0 on 2025-12-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homestays',
            fields=[
                ('HomestayID', models.AutoField(primary_key=True, serialize=False)),
                ('hostID', models.IntegerField()),
            ],
        ),
    ]
