# Generated by Django 6.0 on 2025-12-18 23:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('homestays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestays',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestays',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestays',
            name='crated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestays',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestays',
            name='max_guests',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestays',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestays',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=222, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homestays',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homestays',
            name='hostID',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'HOST'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
