# Generated by Django 6.0 on 2025-12-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0002_homestayimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(help_text='Tên phòng hoặc số phòng (ví dụ: Phòng 101, Phòng Deluxe)', max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_guests', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ava', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='ava', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='homestays.homestays')),
            ],
        ),
    ]
