# Generated by Django 6.0 on 2025-12-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
