# Generated by Django 6.0 on 2026-01-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0004_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', max_length=12),
        ),
    ]
