# Generated by Django 6.0 on 2026-01-19 02:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestays', '0005_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestayimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
