# Generated by Django 6.0 on 2025-12-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
