# Generated by Django 6.0 on 2025-12-23 00:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostprofile',
            name='identity_number',
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='citizen_id_number',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='bank_account',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
