# Generated by Django 6.0 on 2025-12-23 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_hostprofile_identity_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id_number', models.CharField(max_length=12)),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
