# Generated by Django 6.0 on 2026-01-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
